<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDu9t8sq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDu9t8sq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDu9t8sq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDu9t8sq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDu9t8sq\appProdProjectContainer(array(
    'container.build_hash' => 'Du9t8sq',
    'container.build_id' => 'af12357b',
    'container.build_time' => 1551989277,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDu9t8sq');
