<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ActivoFijoItem extends \AppBundle\Entity\ActivoFijoItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'operando', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'tipoActivo', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'tipoPersona', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'orden'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'operando', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'tipoActivo', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'tipoPersona', '' . "\0" . 'AppBundle\\Entity\\ActivoFijoItem' . "\0" . 'orden'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ActivoFijoItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoActivo', []);

        return parent::getTipoActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoActivo($tipoActivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoActivo', [$tipoActivo]);

        return parent::setTipoActivo($tipoActivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoPersona', []);

        return parent::getTipoPersona();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoPersona($tipoPersona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoPersona', [$tipoPersona]);

        return parent::setTipoPersona($tipoPersona);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperando()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperando', []);

        return parent::getOperando();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperando($operando)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperando', [$operando]);

        return parent::setOperando($operando);
    }

}
